import './globals.css';
import type { Metadata } from 'next';
import TopBar from './components/TopBar/TopBar';
import { ReduxProvider } from './redux/provider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

export const metadata: Metadata = {
  title: 'Shopping',
  description: 'Generated by create next app',
}

export default function RootLayout( { children } : { children: React.ReactNode }) {

  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <ToastContainer
            position="bottom-center"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="dark"
          />
          <TopBar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  )
}
